# -*- coding: utf-8 -*-
"""Raouter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmntFOPjJ6CiQ8QPU-T3-USWYn0PP8DB
"""

# Install langchain_groq
#!pip install langchain-groq

# Install required libraries
# !pip install langchain-groq langchain-community

"""**Router Setup (The Logic)**"""



from typing import Literal
from pydantic import BaseModel, Field
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
import os
# Memory imports
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory

# 1. Define Output Schema with all routing options
class RouteQuery(BaseModel):
    """Route the user query to the most appropriate specialized agent."""
    destination: Literal["product_search", "order_tracking", "faq_agent", "chitchat", "out_of_scope"] = Field(
        ...,
        description="Select the appropriate destination based on user intent and history."
    )

# 2. Build the Router using Groq with Llama 3.3
from dotenv import load_dotenv
load_dotenv()

def create_router():
    # Initialize LLM with your API Key from Google Colab Secrets
    llm = ChatGroq(
        model="llama-3.1-8b-instant",
        groq_api_key=os.getenv('GROQ_API_KEY'),
        temperature=0
    )

    # Force the LLM to output according to the RouteQuery schema
    structured_llm_router = llm.with_structured_output(RouteQuery)

    # System instructions to guide the routing logic
    system_prompt = """You are an expert router for 'High Tech' e-commerce support.
    
    YOUR JOB: Route the user's NEW message to the correct agent. Focus ONLY on the NEW message intent.

    ROUTING RULES (check in this order):

    faq_agent — If the NEW message asks about ANY of these topics:
      delivery, shipping, توصيل, شحن, بتوصلوا, بتشحنوا,
      return, refund, ارجع, ارجعه, استرجاع, ارجاع, استبدال,
      warranty, ضمان, كفالة,
      installment, تقسيط, اقسط, أقساط,
      payment, دفع, فلوس, كاش,
      policy, سياسة,
      contact, phone, call, اتصل, رقم, واتساب, WhatsApp, email, ايميل, تليفون المحل, رقم المحل,
      support, مساعدة, خدمة العملاء, شكوى

    order_tracking — If the NEW message asks about THEIR specific order:
      order status, tracking, فين الاوردر, طلبي, شحنتي, رقم الطلب

    product_search — If the NEW message asks about products, prices, specs, buying advice, or what's available.
      EXAMPLES: عاوز, سعر, كام, ايه عندكم, عندكوا, عندكم, متاح,
      سماعات, سماعة, موبايل, تليفون, تليفونات, ساعات, ساعة, لابتوب, شاشة,
      ماوس, كيبورد, باور بانك, شاحن, ايفون, سامسونج, أبل, سوني,
      recommend, compare, price, headphones, phone, watch, laptop
      IMPORTANT: If the message mentions ANY product category (phones, watches, headphones, etc.), route to product_search.

    chitchat — ONLY for pure greetings, thanks, or casual chat with NO product mention:
      مرحبا, أهلا, شكرا, hello, hi, thanks, bye, هاى, هاي

    out_of_scope — ONLY if the message is completely unrelated to electronics or shopping (cooking, weather, math, etc.)
    
    PRIORITY: product mentions > everything else. "عندكوا ساعات" = product_search (NOT chitchat).
    IMPORTANT: When in doubt between chitchat and product_search, choose product_search.
    CRITICAL: Route based on the NEW message ONLY."""

    # Create prompt template — Route ONLY based on the new message
    route_prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])

    return route_prompt | structured_llm_router

# --- Memory Storage Management ---
store = {} # In-memory dictionary to hold history for each user session

def get_session_history(session_id: str) -> BaseChatMessageHistory:
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]

# 3. Initialize the base chain and wrap it with Memory support
base_router_chain = create_router()

class RouterWrapper:
    # كلمات مفتاحية مضمونة — لو لقيناها نوجه من غير ما نسأل الـ LLM
    FAQ_KEYWORDS = [
        'توصيل', 'شحن', 'بتوصلوا', 'بتشحنوا', 'delivery', 'shipping',
        'استرجاع', 'ارجاع', 'ارجعه', 'ارجع', 'استبدال', 'return', 'refund',
        'ضمان', 'كفالة', 'warranty',
        'تقسيط', 'اقسط', 'أقساط', 'installment',
        'سياسة', 'policy',
        'اتصل', 'واتساب', 'whatsapp', 'ايميل', 'email', 'رقم المحل',
        'خدمة العملاء', 'شكوى', 'support'
    ]
    PRODUCT_KEYWORDS = [
        'سماعات', 'سماعة', 'موبايل', 'تليفون', 'تليفونات', 'ساعات', 'ساعة',
        'لابتوب', 'شاشة', 'ماوس', 'كيبورد', 'باور بانك', 'شاحن',
        'ايفون', 'آيفون', 'سامسونج', 'أبل', 'سوني', 'شاومي', 'ون بلس',
        'headphone', 'phone', 'watch', 'laptop', 'iphone', 'samsung', 'apple',
        'سعر', 'كام', 'عندكوا', 'عندكم', 'ايه عندكم', 'متاح', 'انواع',
        'sony', 'beats', 'jbl', 'airpods', 'galaxy'
    ]
    ORDER_KEYWORDS = ['فين الاوردر', 'طلبي', 'شحنتي', 'رقم الطلب', 'tracking', 'order status']
    CHITCHAT_ONLY = ['مرحبا', 'أهلا', 'اهلا', 'شكرا', 'hello', 'hi', 'thanks', 'bye', 'هاى', 'هاي', 'السلام عليكم']

    def _keyword_route(self, text):
        """Deterministic keyword routing — 100% accurate for clear cases."""
        text_lower = text.lower().strip()
        
        # Check FAQ first (delivery, returns, warranty, contact)
        for kw in self.FAQ_KEYWORDS:
            if kw in text_lower:
                return "faq_agent"
        
        # Check order tracking
        for kw in self.ORDER_KEYWORDS:
            if kw in text_lower:
                return "order_tracking"
        
        # Check product search
        for kw in self.PRODUCT_KEYWORDS:
            if kw in text_lower:
                return "product_search"
        
        # Check if it's PURE chitchat (no product words)
        if text_lower in self.CHITCHAT_ONLY or (len(text_lower) < 15 and any(kw == text_lower for kw in self.CHITCHAT_ONLY)):
            return "chitchat"
        
        return None  # Ambiguous — let LLM decide

    def invoke(self, inputs, config=None):
        session_id = config.get("configurable", {}).get("session_id", "default")
        user_input = inputs["input"]
        
        # 1. Try keyword-based routing first (deterministic, 100% accurate)
        keyword_result = self._keyword_route(user_input)
        
        if keyword_result:
            # Create a result object matching the expected format
            result = type('Route', (), {'destination': keyword_result})()
        else:
            # 2. Fallback to LLM for ambiguous cases
            result = base_router_chain.invoke({"input": user_input})
        
        # Save user message to session history
        history = get_session_history(session_id)
        history.add_user_message(user_input)
        return result

router_with_memory = RouterWrapper()

print("[SUCCESS] Full Router System with Memory & Llama 3.3 is ready!")



"""**Testing Functions**"""

# 4. Function to test the router with session support
def ask_router_with_memory(user_input, session_id="default_user"):
    try:
        # Pass the session_id to the config
        config = {"configurable": {"session_id": session_id}}

        # Invoke the memory-enabled chain
        response = router_with_memory.invoke(
            {"input": user_input},
            config=config
        )

        decision = response.destination.upper()

        # Handle specific visual feedback for different decisions
        icon = "➡️"
        if decision == "CHITCHAT": icon = "👋"
        if decision == "OUT_OF_SCOPE": icon = "❌"

        print(f"--- Router Test (Session: {session_id}) ---")
        print(f"User: {user_input}")
        print(f"Decision: {icon} {decision}")
        print(f"----------------------\n")

    except Exception as e:
        print(f"Oops! Something went wrong: {e}")



"""**Interactive Tester (The Loop)**"""

# 5. Interactive Chat Session to test Memory and Logic
def interactive_test():
    print("🤖 Router Tester Active. Type 'exit' to quit or 'new' to reset.")
    print("-" * 50)

    # Start with a default session
    current_session = "amany_session_1"

    while True:
        user_query = input(f"[{current_session}] Ask: ")

        # Exit condition
        if user_query.lower() in ['exit', 'quit', 'خروج']:
            print("Exiting tester. Success!")
            break

        # Reset memory for a new user/session
        if user_query.lower() in ['new', 'reset', 'جديد']:
            import uuid
            current_session = f"session_{str(uuid.uuid4())[:4]}"
            print(f"✨ Session reset. New ID: {current_session}")
            continue

        # Run the test
        ask_router_with_memory(user_query, session_id=current_session)

# Start the interactive testing
if __name__ == "__main__":
    interactive_test()

